name: build and publish a release

on:
  release:
    types: [published]

jobs:
  build-upload:
    runs-on: macOS-latest
    permissions:
      contents: read
      packages: write
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v4
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
      - name: Upload
        run: ./gradlew --stacktrace publishAllPublicationsToGitHubPackagesRepository
        shell: bash
