name: build and publish a snapshot

on:
  push:
    branches:
      - main
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:
  build-upload:
    runs-on: macOS-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.sonatype_username }}
      SONATYPE_PASSWORD: ${{ secrets.sonatype_password }}
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
      - name: Upload
        # Disabled for now as we don't have a snapshots repo on GH Packages
        if: false
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository -PgitRef=${{ github.ref }} -Psnapshot=true
        shell: bash
