name: check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  check:
    runs-on: macOS-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v4
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
