name: check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
